title: yk-work-journal
description: >-
  A personal work journal powered by Jekyll and GitHub Pages.
# Use the Cayman theme for GitHub Pages
theme: jekyll-theme-cayman
# Set the baseurl to "/yk-work-journal" if using a project site (not a user/organization site)
# baseurl: "/yk-work-journal"
# url: "https://ykhan-sys.github.io"

# Build settings
markdown: kramdown
